version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
      - redis
    environment:
      REDIS_URL: redis://redis:6379
      DB_HOST: mariadb

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: images
      MYSQL_USER: hugh
      MYSQL_PASSWORD: password
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  mariadb_data: {}
